name: Test and build chat-io-server

on:
  workflow_dispatch:
    paths:
      - src/**
  push:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install libs
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install libs
        run: npm i

      - name: Build the app
        run: npm run build
